version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./web:/srv/web
      - caddy_data:/data
    cap_add:
      - NET_ADMIN
    environment:
      - SITE_ADDRESS=hylo.ink
      - PICFIT_HOST=picfit

  picfit:
    image: thoas/picfit:0.2.1
    container_name: picfit
    ports:
      - "3001:3001"
    environment:
      - PICFIT_CONFIG_PATH=/picfit-config.json
    volumes:
      - ./picfit-config.json:/picfit-config.json
      - type: bind
        source: ./export
        target: /export

volumes:
  caddy_data:
